<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="VEV-IN" ignored="2" name="ClassAandB(failed)" tests="1" failures="1" timestamp="10 Sep 2020 19:07:23 GMT" time="0.153" errors="0">
  <testcase name="tcA2" time="0.043" classname="org.oracle.ManualReRun">
    <failure type="java.lang.AssertionError" message="Assert Failure in tcA2 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Assert Failure in tcA2 expected [true] but found [false]
at org.oracle.ManualReRun.tcA2(ManualReRun.java:15)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- tcA2 -->
  <testcase name="tcA1" time="0.0" classname="org.oracle.ManualReRun">
    <ignored/>
  </testcase> <!-- tcA1 -->
  <testcase name="tcA3" time="0.0" classname="org.oracle.ManualReRun">
    <ignored/>
  </testcase> <!-- tcA3 -->
</testsuite> <!-- ClassAandB(failed) -->
